#!/usr/bin/env node
// Builds hooks/engine.js: src/core.js, src/sprite.js and every anims/*.js (each in its own scope)
// as one ES module. Run it after changing src/ or anims/; the output is committed because a
// plugin install runs the repository as it is.
//
// usage: node tools/build.js
const fs = require('fs')
const path = require('path')
const vm = require('vm')

const ROOT = path.join(__dirname, '..')
const read = (f) => fs.readFileSync(path.join(ROOT, f), 'utf8')

const files = fs.readdirSync(path.join(ROOT, 'anims')).filter((f) => /^[a-z0-9-]+\.js$/.test(f)).sort()
let failed = 0
const anims = files.map((f) => {
  const code = `;(function () {\ntry {\n${read(`anims/${f}`).trimEnd()}\n} catch (e) {}\n})()\n`
  try {
    new vm.Script(`'use strict'\n${code}`, { filename: `anims/${f}` })
  } catch (e) {
    failed++
    console.error(`anims/${f}: ${e.message}`)
  }
  return code
})
if (failed) process.exit(1)

const exported = ['$cdL', '$cdNext', '$cdPick', '$cdPlay', '$cdRuns', '$cdPose', '$cdCol', '$cdInt', '$cdMs', '$cdIdle', '$cdH', '$cdG', '$cdSprite', '$cdPalette']
const out = [
  '// Generated by tools/build.js from src/ and anims/. Do not edit.',
  read('src/core.js'),
  read('src/sprite.js'),
  ...anims,
  `export { ${exported.join(', ')} }`,
  '',
].join('\n')

fs.writeFileSync(path.join(ROOT, 'hooks', 'engine.js'), out)
console.log(`hooks/engine.js: ${files.length} animations, ${Math.round(out.length / 1024)} KB`)
