// Clawd's 9x3 sprite (the glyph tables Claude Code draws him with) and the dark theme's
// colours, which theme names in animations resolve to.
var $cdSprite = {
  // Named poses, as {eyes, arms, feet}.
  poses: {
    "default": { eyes: "open", arms: "down", feet: "both" },
    "arms-up": { eyes: "open", arms: "up", feet: "both" },
    "look-left": { eyes: "left", arms: "down", feet: "both" },
    "look-right": { eyes: "right", arms: "down", feet: "both" },
  },
  // Arm glyphs: row 0 left (cols 0-1) and right (col 8), row 1 left (cols 0-1) and right (cols 7-8).
  arms: {
    "down": { r1L: " ▐", r1R: "", r2L: "▝▜", r2R: "█▀" },
    "up": { r1L: "▗▟", r1R: "▄", r2L: " ▜", r2R: "█▘" },
    "one-up": { r1L: " ▐", r1R: "▄", r2L: "▝▜", r2R: "█▘" },
  },
  // Eye glyphs from col 2 of row 0, drawn on black; a lid span inverts.
  eyes: {
    "open": [{ glyphs: "▛███▛█" }],
    "left": [{ glyphs: "▟███▟█" }],
    "right": [{ glyphs: "█▟███▟" }],
    "closed": [{ glyphs: "▂", lid: true }, { glyphs: "███" }, { glyphs: "▂", lid: true }, { glyphs: "█" }],
    "wink": [{ glyphs: "▛███" }, { glyphs: "▂", lid: true }, { glyphs: "█" }],
  },
  // Row 2.
  feet: {
    "both": " ▝▝   ▝▝ ",
    "left": " ▝▝      ",
    "right": "      ▝▝ ",
  },
  // Turning frames: three rows each; cols from..to sit on black.
  facing: {
    "right-12": [{ glyphs: " ▐█▜██▛█ ", from: 2, to: 8 }, { glyphs: "▝▜██████▀", from: 2, to: 7 }, { glyphs: " ▝▝   ▝▝ ", from: 0, to: 0 }],
    "right-30": [{ glyphs: "  █▛██▛▌ ", from: 2, to: 7 }, { glyphs: " ▝█████▛ ", from: 2, to: 7 }, { glyphs: "  ▘▘  ▘▘ ", from: 0, to: 0 }],
    "right-55": [{ glyphs: "  ▐█▛█▜  ", from: 3, to: 7 }, { glyphs: "  ▐████  ", from: 3, to: 7 }, { glyphs: "  ▝▝ ▝▝  ", from: 0, to: 0 }],
    "right-75": [{ glyphs: "   ██▛▌  ", from: 3, to: 6 }, { glyphs: "   ███▌  ", from: 3, to: 6 }, { glyphs: "   ▘  ▘  ", from: 0, to: 0 }],
    "edge": [{ glyphs: "   ▐██   ", from: 4, to: 6 }, { glyphs: "   ▐██   ", from: 4, to: 6 }, { glyphs: "   ▝ ▝   ", from: 0, to: 0 }],
    "back-105": [{ glyphs: "   ███▌  ", from: 3, to: 6 }, { glyphs: "   ███▌  ", from: 3, to: 6 }, { glyphs: "   ▘  ▘  ", from: 0, to: 0 }],
    "back-125": [{ glyphs: "  ▐████  ", from: 3, to: 7 }, { glyphs: "  ▐████  ", from: 3, to: 7 }, { glyphs: "  ▝▝ ▝▝  ", from: 0, to: 0 }],
    "back-150": [{ glyphs: "  █████▌ ", from: 2, to: 7 }, { glyphs: " ▝█████▛ ", from: 2, to: 7 }, { glyphs: "  ▘▘  ▘▘ ", from: 0, to: 0 }],
    "back": [{ glyphs: " ▐██████ ", from: 2, to: 8 }, { glyphs: "▝▜██████▀", from: 2, to: 7 }, { glyphs: " ▝▝   ▝▝ ", from: 0, to: 0 }],
    "left-75": [{ glyphs: "   ▛██▌  ", from: 3, to: 6 }, { glyphs: "   ███▌  ", from: 3, to: 6 }, { glyphs: "   ▘  ▘  ", from: 0, to: 0 }],
    "left-55": [{ glyphs: "  ▐▜▛██  ", from: 3, to: 7 }, { glyphs: "  ▐████  ", from: 3, to: 7 }, { glyphs: "  ▝▝ ▝▝  ", from: 0, to: 0 }],
    "left-30": [{ glyphs: "  ▛██▛█▌ ", from: 2, to: 7 }, { glyphs: " ▝█████▛ ", from: 2, to: 7 }, { glyphs: "  ▘▘  ▘▘ ", from: 0, to: 0 }],
    "left-12": [{ glyphs: " ▐▛███▜█ ", from: 2, to: 8 }, { glyphs: "▝▜██████▀", from: 2, to: 7 }, { glyphs: " ▝▝   ▝▝ ", from: 0, to: 0 }],
  },
}

var $cdPalette = {
  clawd_body: 0xd77757,
  clawd_background: 0x000000,
  claude: 0xd77757,
  claudeShimmer: 0xeb9f7f,
  permission: 0xb1b9f9,
  permissionShimmer: 0xcfd7ff,
  suggestion: 0xb1b9f9,
  success: 0x4eba65,
  error: 0xff6b80,
  warning: 0xffc107,
  warningShimmer: 0xffdf39,
  inactive: 0x999999,
  inactiveShimmer: 0xc1c1c1,
  subtle: 0x505050,
  text: 0xffffff,
  inverseText: 0x000000,
  remember: 0xb1b9f9,
  background: 0x00cccc,
  autoAccept: 0xaf87ff,
  bashBorder: 0xfd5db1,
  planMode: 0x48968c,
  ide: 0x4782c8,
  fastMode: 0xff7814,
  fastModeShimmer: 0xffa546,
  effortUltra: 0xaf87ff,
  professionalBlue: 0x6a9bcc,
  chromeYellow: 0xfbbc04,
  merged: 0xaf87ff,
  diffAdded: 0x225c2b,
  diffRemoved: 0x7a2936,
  diffAddedWord: 0x38a660,
  diffRemovedWord: 0xb3596b,
  rainbow_red: 0xeb5f57,
  rainbow_orange: 0xf58b57,
  rainbow_yellow: 0xfac35f,
  rainbow_green: 0x91c882,
  rainbow_blue: 0x82aadc,
  rainbow_indigo: 0x9b82c8,
  rainbow_violet: 0xc882b4,
  rainbow_red_shimmer: 0xfa9b93,
  rainbow_orange_shimmer: 0xffb989,
  rainbow_yellow_shimmer: 0xffe19b,
  rainbow_green_shimmer: 0xb9e6b4,
  rainbow_blue_shimmer: 0xb4cdf0,
  rainbow_indigo_shimmer: 0xc3b4e6,
  rainbow_violet_shimmer: 0xe6b4d2,
}
